void byteToString (unsigned char sym, char* storage);
void writeStringOfBinaries (unsigned char* pToBinData, char* outString, int bytesToConvert);
void convertBinariesIntoBlock (unsigned char* pToBinaries, char* outBuffer, int bytesPerRow, int numOfRows);
void setTextToGreen (HANDLE console);
void setTextToMagenta (HANDLE console);
void setTextToRed (HANDLE console);
void setTextToWhite (HANDLE console);
int openFilePrompt (FILE** fPointer, int* pFileSize, HANDLE console);
void plotBinaryBlockOfSymbols (unsigned char* pToBinaries, int bytesToShow, int startRow, HANDLE console );
int readDisplayUp (FILE** fPointer, HANDLE console, int fileSize, int chunkSize);
int readDisplayDown (FILE** fPointer, HANDLE console, int fileSize, int chunkSize);
void plotBinaryBlockOfSymbolsAsString (unsigned char* pToBinaries, int bytesToShow,  HANDLE console );
int readAndShowFullFile (FILE** fPointer, HANDLE console,  int numbSymbPerView);
void plotToFileBinaryBlockOfSymbolsAsString (FILE** fOutFile,unsigned char* pToBinaries, int bytesToShow);
int readAndConvertFullFile (FILE** fPointer, FILE** fDest,  int numbSymbPerView);